IF NOT EXISTS CREATE TABLE Task (
    TaskID TEXT PRIMARY KEY,
    CreatedTime TEXT NOT NULL
);

IF NOT EXISTS CREATE TABLE TaskTitleInfo (
    TaskTitleID TEXT PRIMARY KEY,
    TaskID TEXT NOT NULL,
    UpdatedTime TEXT NOT NULL,
    Title TEXT NOT NULL
);

IF NOT EXISTS CREATE TABLE CheckStateInfo (
    CheckStateID TEXT PRIMARY KEY,
    TaskID TEXT NOT NULL,
    UpdatedTime TEXT NOT NULL,
    IsChecked TEXT NOT NULL
);

IF NOT EXISTS CREATE TABLE LimitInfo (
    LimitID TEXT PRIMARY KEY,
    TaskID TEXT NOT NULL,
    UpdatedTime TEXT NOT NULL,
    LimitTime Text
);

IF NOT EXISTS CREATE TABLE BoardInfo (
    BoardInfoID TEXT PRIMARY KEY,
    TaskID TEXT NOT NULL,
    UpdatedTime TEXT NOT NULL,
    BoardName TEXT NOT NULL
);